/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TouristLocationService } from "../touristLocation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TouristLocationCreateInput } from "./TouristLocationCreateInput";
import { TouristLocation } from "./TouristLocation";
import { TouristLocationFindManyArgs } from "./TouristLocationFindManyArgs";
import { TouristLocationWhereUniqueInput } from "./TouristLocationWhereUniqueInput";
import { TouristLocationUpdateInput } from "./TouristLocationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TouristLocationControllerBase {
  constructor(
    protected readonly service: TouristLocationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TouristLocation })
  @nestAccessControl.UseRoles({
    resource: "TouristLocation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTouristLocation(
    @common.Body() data: TouristLocationCreateInput
  ): Promise<TouristLocation> {
    return await this.service.createTouristLocation({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        latitude: true,
        location: true,
        longitude: true,
        mapsUrl: true,
        name: true,
        pictures: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TouristLocation] })
  @ApiNestedQuery(TouristLocationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TouristLocation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async touristLocations(
    @common.Req() request: Request
  ): Promise<TouristLocation[]> {
    const args = plainToClass(TouristLocationFindManyArgs, request.query);
    return this.service.touristLocations({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        latitude: true,
        location: true,
        longitude: true,
        mapsUrl: true,
        name: true,
        pictures: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TouristLocation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TouristLocation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async touristLocation(
    @common.Param() params: TouristLocationWhereUniqueInput
  ): Promise<TouristLocation | null> {
    const result = await this.service.touristLocation({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        latitude: true,
        location: true,
        longitude: true,
        mapsUrl: true,
        name: true,
        pictures: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TouristLocation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TouristLocation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTouristLocation(
    @common.Param() params: TouristLocationWhereUniqueInput,
    @common.Body() data: TouristLocationUpdateInput
  ): Promise<TouristLocation | null> {
    try {
      return await this.service.updateTouristLocation({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          latitude: true,
          location: true,
          longitude: true,
          mapsUrl: true,
          name: true,
          pictures: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TouristLocation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TouristLocation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTouristLocation(
    @common.Param() params: TouristLocationWhereUniqueInput
  ): Promise<TouristLocation | null> {
    try {
      return await this.service.deleteTouristLocation({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          latitude: true,
          location: true,
          longitude: true,
          mapsUrl: true,
          name: true,
          pictures: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
